// lib/admin_main.dart - DEDICATED ENTRY POINT FOR THE WEB BUILD (ADMIN DASHBOARD)

import 'package:flutter/material.dart';
import 'admin_main_screen.dart'; // Launches the main screen that manages all admin pages.

// Import the necessary Firebase Core package 
import 'package:firebase_core/firebase_core.dart';
// Import the configuration file generated by the FlutterFire CLI
import 'firebase_options.dart'; 


void main() async {
  // Ensure Flutter is initialized before calling native-related code
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase (if the Admin Dashboard needs access to your backend)
  // Ensure 'firebase_options.dart' has been generated by the FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const AdminApp());
}

class AdminApp extends StatelessWidget {
  const AdminApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Set the title for the web browser tab
      title: 'Laundry Admin Dashboard',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.purple.shade900), 
        useMaterial3: true,
      ),
      // Launches the Stateful widget that contains the sidebar and navigation logic.
      home: const AdminMainScreen(), 
    );
  }
}