// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1_KYj8fuR0w6clViolfVv6sy5WDafYIc',
    appId: '1:232944609082:web:e5f1d8a791571684bfd203',
    messagingSenderId: '232944609082',
    projectId: 'washsync-a3314',
    authDomain: 'washsync-a3314.firebaseapp.com',
    storageBucket: 'washsync-a3314.firebasestorage.app',
    measurementId: 'G-MCLG4E2PZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP5ZIsa1uJfvoPbHcnBGxC06tZlN53ArA',
    appId: '1:232944609082:android:c73f528fa8891964bfd203',
    messagingSenderId: '232944609082',
    projectId: 'washsync-a3314',
    storageBucket: 'washsync-a3314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABl7BH8c8MgMf2Oss0aE9muIIFhpQlQt0',
    appId: '1:232944609082:ios:589672ce3c7cf5d4bfd203',
    messagingSenderId: '232944609082',
    projectId: 'washsync-a3314',
    storageBucket: 'washsync-a3314.firebasestorage.app',
    iosBundleId: 'com.example.washsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABl7BH8c8MgMf2Oss0aE9muIIFhpQlQt0',
    appId: '1:232944609082:ios:589672ce3c7cf5d4bfd203',
    messagingSenderId: '232944609082',
    projectId: 'washsync-a3314',
    storageBucket: 'washsync-a3314.firebasestorage.app',
    iosBundleId: 'com.example.washsyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1_KYj8fuR0w6clViolfVv6sy5WDafYIc',
    appId: '1:232944609082:web:39f3b5ddaf527315bfd203',
    messagingSenderId: '232944609082',
    projectId: 'washsync-a3314',
    authDomain: 'washsync-a3314.firebaseapp.com',
    storageBucket: 'washsync-a3314.firebasestorage.app',
    measurementId: 'G-8HZ4L7BFT9',
  );
}
