import 'package:flutter/material.dart';
// 1. FIX: Import the necessary Firebase Core package
import 'package:firebase_core/firebase_core.dart';
// 2. FIX: Import the configuration file generated by the FlutterFire CLI
import 'firebase_options.dart'; 

import 'home_page.dart'; 

// 3. FIX: The main function must be marked 'async' to use 'await'
void main() async {
  // 4. FIX: This line must be the first call if you use plugins before runApp
  WidgetsFlutterBinding.ensureInitialized();
  
  // 5. FIX: Correct method name is initializeApp (case-sensitive)
  //        It also requires the options argument from the generated file.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Laundry App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      // Note: You can add 'const' back here if the MyHomePage widget 
      // is also a StatelessWidget or StatefulWidget and its parameters 
      // are constant (which 'title' usually is).
      home: const MyHomePage(title: 'Flutter Demo Home Page'), 
    );
  }
}